### ISSUE TITLE
Angular universal support 

### ISSUE THREAD

**Issue by ysus** [lexzhukov/ngx-siema#51]
support angular universal 
ReferenceError: document is not defined
    at new e (C:\src\webapp-intertours\dist\server.js:155924:1428)
    at NgxSiemaComponent.ngAfterViewInit (C:\src\webapp-intertours\dist\server.js:155652:25)
    at callProviderLifecycles (C:\src\webapp-intertours\dist\server.js:11607:18)
    at callElementProvidersLifecycles (C:\src\webapp-intertours\dist\server.js:11582:13)
    at callLifecycleHooksChildrenFirst (C:\src\webapp-intertours\dist\server.js:11566:17)
    at checkAndUpdateView (C:\src\webapp-intertours\dist\server.js:12671:5)
    at callViewAction (C:\src\webapp-intertours\dist\server.js:13028:21)
    at execComponentViewsAction (C:\src\webapp-intertours\dist\server.js:12960:13)
    at checkAndUpdateView (C:\src\webapp-intertours\dist\server.js:12669:5)
    at callViewAction (C:\src\webapp-intertours\dist\server.js:13028:21)

**Comment by J4cku** [comment]
I am not sure if that is actually a bug on ngx-siema since Universal does not have document (as it's sever side rendered). I would recommend showing siema only in browser (using isPlatformBrowser)
